### ISSUE TITLE
Is the demo broken?

### ISSUE THREAD

**Issue by mrmartineau** [cferdinandi/sticky-footer#16]
The demo looks broken because the footer is just below the fold, is this correct?

**Comment by cferdinandi** [comment]
No, that's just a result of me not having any sort of reset or normalization on the page. The `body` element. It has a top and bottom padding in some browsers that pushes everything a bit further down the page.

**Comment by mrmartineau** [comment]
It doesn't look like a reset issue (although that might help) because the footer is hidden by the same amount as it's height..

**Comment by cferdinandi** [comment]
View source, find the `style` section in the `head`, and add:

```
* {
    margin: 0;
    padding: 0;
}
```

Issue fixed. I use this on TONS of projects, always with a reset or normalize, and it works as expected.
